models:
  - name: dev_main_file_binary_ts
    columns: 
    - name: file_content
      tests: 
        - generic_not_null
    - name: file_path
      tests: 
        - generic_not_null
        - generic_file_path_regex
    - name: file_name
      tests: 
        - generic_not_null
    - name: modification_time
      tests: 
        - generic_not_null